export const GET_LOCATION_DATA_SUCCESS = 'GET_LOCATION_DATA_SUCCESS';
export const GET_GEO_CODE_SUCCESS = 'GET_GEO_CODE_SUCCESS';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';